<?php
/**
 * Themacle Pagination Component
 *
 * Renders pagination in one of three styles:
 *   - numbers:   Full numeric pagination via paginate_links().
 *   - simple:    Previous / Next links only.
 *   - load-more: A "Load more" button for AJAX-driven loading.
 *
 * @package FlavorChatIA
 *
 * @var string $estilo            Pagination style: 'numbers', 'simple', or 'load-more'.
 * @var string $component_classes Additional CSS classes for the wrapper.
 */

defined( 'ABSPATH' ) || exit;

$estilo            = $estilo ?? 'numbers';
$component_classes = $component_classes ?? '';

$estilos_permitidos = array( 'numbers', 'simple', 'load-more' );
if ( ! in_array( $estilo, $estilos_permitidos, true ) ) {
    $estilo = 'numbers';
}

global $wp_query;

$pagina_actual       = max( 1, get_query_var( 'paged', 1 ) );
$total_paginas       = isset( $wp_query->max_num_pages ) ? (int) $wp_query->max_num_pages : 1;
$tiene_paginacion    = $total_paginas > 1;
?>

<nav class="flavor-pagination w-full py-6 <?php echo esc_attr( $component_classes ); ?>" aria-label="<?php echo esc_attr__( 'Paginación', FLAVOR_PLATFORM_TEXT_DOMAIN ); ?>">

    <?php
    /* ---------------------------------------------------------------------- */
    /*  Style: numbers                                                         */
    /* ---------------------------------------------------------------------- */
    ?>
    <?php if ( 'numbers' === $estilo ) : ?>

        <?php if ( $tiene_paginacion ) : ?>

            <div class="flavor-pagination--numbers flex justify-center items-center gap-1">
                <?php
                $enlaces_paginacion = paginate_links( array(
                    'total'     => $total_paginas,
                    'current'   => $pagina_actual,
                    'type'      => 'array',
                    'prev_text' => '<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path></svg>',
                    'next_text' => '<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path></svg>',
                ) );

                if ( ! empty( $enlaces_paginacion ) && is_array( $enlaces_paginacion ) ) :
                    foreach ( $enlaces_paginacion as $enlace_html ) :

                        $es_pagina_activa = strpos( $enlace_html, 'current' ) !== false;
                        $es_enlace_puntos = strpos( $enlace_html, 'dots' ) !== false;

                        if ( $es_pagina_activa ) :
                            /*
                             * Active page: <span> with primary background.
                             * We extract the text content and render our own markup
                             * to ensure consistent styling.
                             */
                            $numero_pagina = wp_strip_all_tags( $enlace_html );
                            ?>
                            <span
                                class="inline-flex items-center justify-center w-10 h-10 rounded-lg text-sm font-semibold text-white"
                                style="background-color: var(--flavor-primary, #2563eb);"
                                aria-current="page"
                            >
                                <?php echo esc_html( $numero_pagina ); ?>
                            </span>
                            <?php

                        elseif ( $es_enlace_puntos ) :
                            ?>
                            <span class="inline-flex items-center justify-center w-10 h-10 text-sm" style="color: var(--flavor-text, #6b7280);">
                                &hellip;
                            </span>
                            <?php

                        else :
                            /*
                             * Regular page link. We wrap the original anchor in a
                             * styled container. The anchor tag already has the href
                             * generated by paginate_links().
                             */
                            $enlace_estilizado = str_replace(
                                '<a ',
                                '<a class="inline-flex items-center justify-center w-10 h-10 rounded-lg text-sm font-medium transition-all duration-200 hover:text-white" style="color: var(--flavor-text, #374151); background-color: var(--flavor-bg-alt, #f3f4f6);" onmouseover="this.style.backgroundColor=\'var(--flavor-primary, #2563eb)\'" onmouseout="this.style.backgroundColor=\'var(--flavor-bg-alt, #f3f4f6)\';this.style.color=\'var(--flavor-text, #374151)\'" ',
                                $enlace_html
                            );
                            echo wp_kses_post( $enlace_estilizado );
                        endif;

                    endforeach;
                endif;
                ?>
            </div>

        <?php endif; ?>

    <?php
    /* ---------------------------------------------------------------------- */
    /*  Style: simple                                                          */
    /* ---------------------------------------------------------------------- */
    ?>
    <?php elseif ( 'simple' === $estilo ) : ?>

        <?php if ( $tiene_paginacion ) : ?>

            <div class="flavor-pagination--simple flex justify-center items-center gap-4">

                <?php
                $url_pagina_anterior = get_previous_posts_page_link();
                $url_pagina_siguiente = get_next_posts_page_link( $total_paginas );
                $esta_en_primera_pagina = ( $pagina_actual <= 1 );
                $esta_en_ultima_pagina  = ( $pagina_actual >= $total_paginas );
                ?>

                <?php if ( ! $esta_en_primera_pagina ) : ?>
                    <a
                        href="<?php echo esc_url( $url_pagina_anterior ); ?>"
                        class="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg text-sm font-medium transition-all duration-200 hover:shadow-md"
                        style="color: var(--flavor-primary, #2563eb); background-color: var(--flavor-bg-alt, #f3f4f6);"
                    >
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
                        </svg>
                        <?php echo esc_html__( 'Anterior', FLAVOR_PLATFORM_TEXT_DOMAIN ); ?>
                    </a>
                <?php else : ?>
                    <span
                        class="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg text-sm font-medium opacity-40 cursor-not-allowed"
                        style="color: var(--flavor-text, #9ca3af); background-color: var(--flavor-bg-alt, #f3f4f6);"
                        aria-disabled="true"
                    >
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
                        </svg>
                        <?php echo esc_html__( 'Anterior', FLAVOR_PLATFORM_TEXT_DOMAIN ); ?>
                    </span>
                <?php endif; ?>

                <span class="text-sm" style="color: var(--flavor-text, #6b7280);">
                    <?php
                    printf(
                        /* translators: %1$s: current page number, %2$s: total pages */
                        esc_html__( 'Página %1$s de %2$s', FLAVOR_PLATFORM_TEXT_DOMAIN ),
                        esc_html( $pagina_actual ),
                        esc_html( $total_paginas )
                    );
                    ?>
                </span>

                <?php if ( ! $esta_en_ultima_pagina ) : ?>
                    <a
                        href="<?php echo esc_url( $url_pagina_siguiente ); ?>"
                        class="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg text-sm font-medium transition-all duration-200 hover:shadow-md"
                        style="color: var(--flavor-primary, #2563eb); background-color: var(--flavor-bg-alt, #f3f4f6);"
                    >
                        <?php echo esc_html__( 'Siguiente', FLAVOR_PLATFORM_TEXT_DOMAIN ); ?>
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                        </svg>
                    </a>
                <?php else : ?>
                    <span
                        class="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg text-sm font-medium opacity-40 cursor-not-allowed"
                        style="color: var(--flavor-text, #9ca3af); background-color: var(--flavor-bg-alt, #f3f4f6);"
                        aria-disabled="true"
                    >
                        <?php echo esc_html__( 'Siguiente', FLAVOR_PLATFORM_TEXT_DOMAIN ); ?>
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                        </svg>
                    </span>
                <?php endif; ?>

            </div>

        <?php endif; ?>

    <?php
    /* ---------------------------------------------------------------------- */
    /*  Style: load-more                                                       */
    /* ---------------------------------------------------------------------- */
    ?>
    <?php elseif ( 'load-more' === $estilo ) : ?>

        <?php if ( $tiene_paginacion && $pagina_actual < $total_paginas ) : ?>

            <div class="flavor-pagination--load-more flex justify-center">

                <button
                    type="button"
                    class="flavor-load-more-btn inline-flex items-center gap-2 px-8 py-3 rounded-lg text-sm font-semibold text-white transition-all duration-300 hover:shadow-lg hover:-translate-y-0.5 focus:outline-none focus:ring-2 focus:ring-offset-2"
                    style="background-color: var(--flavor-primary, #2563eb); focus-ring-color: var(--flavor-primary, #2563eb);"
                    data-page="<?php echo esc_attr( $pagina_actual ); ?>"
                    data-max-pages="<?php echo esc_attr( $total_paginas ); ?>"
                    aria-label="<?php echo esc_attr__( 'Cargar más elementos', FLAVOR_PLATFORM_TEXT_DOMAIN ); ?>"
                >
                    <span class="flavor-load-more-btn__texto">
                        <?php echo esc_html__( 'Cargar más', FLAVOR_PLATFORM_TEXT_DOMAIN ); ?>
                    </span>

                    <span class="flavor-load-more-btn__spinner hidden" aria-hidden="true">
                        <svg class="animate-spin w-4 h-4" fill="none" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z"></path>
                        </svg>
                    </span>

                    <svg class="flavor-load-more-btn__icono w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
                    </svg>
                </button>

            </div>

            <p class="text-center text-xs mt-3" style="color: var(--flavor-text, #9ca3af);">
                <?php
                $elementos_restantes = $total_paginas - $pagina_actual;
                printf(
                    /* translators: %s: number of remaining pages */
                    esc_html( _n(
                        'Queda %s página por cargar',
                        'Quedan %s páginas por cargar',
                        $elementos_restantes,
                        FLAVOR_PLATFORM_TEXT_DOMAIN
                    ) ),
                    esc_html( number_format_i18n( $elementos_restantes ) )
                );
                ?>
            </p>

        <?php elseif ( $tiene_paginacion && $pagina_actual >= $total_paginas ) : ?>

            <div class="flavor-pagination--load-more-done flex justify-center">
                <p class="text-sm py-3" style="color: var(--flavor-text, #9ca3af);">
                    <?php echo esc_html__( 'Has visto todos los elementos.', FLAVOR_PLATFORM_TEXT_DOMAIN ); ?>
                </p>
            </div>

        <?php endif; ?>

    <?php endif; ?>

</nav>
